apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: sensor-data
  name: sensor-data
  resourceVersion: '247050425' 
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'sensor-data:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    binary: {}
    type: Binary
  strategy:
    dockerStrategy:
      dockerfilePath: Dockerfile
    type: Docker
  triggers: []

